#!/usr/bin/env python3
"""Generate and screen Final Kick spend-gate variants.

This is a local-only search harness. It copies a trusted base agent, injects a
small set of explicit Final Kick knobs, optionally runs the existing
side-swapped paired evaluator, and writes CSV logs. It never submits to Kaggle
and never edits the active submission entry point.

Default intent:
  - base: v67 explorer
  - variants: conservative final-kick gate timings and build-veto modes
  - evaluator: scripts/paired_eval_sides.py::run
"""
from __future__ import annotations

import argparse
import csv
import json
import random
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASE = ROOT / "experiments/v67_antimil_hash/main.py"
DEFAULT_OUT_DIR = ROOT / "experiments/generated_final_kick_search"
DEFAULT_RESULTS = ROOT / "reports/final_kick_knob_search_20260606.csv"
DEFAULT_OPPONENTS = [
    ROOT / "experiments/v67_antimil_hash/main.py",
    ROOT / "experiments/v37_late_save_jump_no_scout/main.py",
    ROOT / "experiments/v24_jump_enemy_factory_avoid/main.py",
    ROOT / "baselines/top2_jump_bfs/main.py",
]


@dataclass(frozen=True)
class Knobs:
    final_kick_turn: int
    final_kick_gap: int
    gate_miner: bool
    gate_scout: bool

    @property
    def mode(self) -> str:
        if self.gate_miner and self.gate_scout:
            return "both"
        if self.gate_miner:
            return "miner"
        if self.gate_scout:
            return "scout"
        return "none"

    @property
    def name(self) -> str:
        return f"fk_t{self.final_kick_turn}_g{self.final_kick_gap}_{self.mode}"


def _replace_once(text: str, old: str, new: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"expected one occurrence of {old!r}, found {count}")
    return text.replace(old, new, 1)


def inject_knobs(base_text: str, knobs: Knobs) -> str:
    """Return a v67-derived agent with a tiny Final Kick knob block injected."""
    text = base_text
    text = text.replace(
        '"""',
        '"""\nGenerated by scripts/search_final_kick_knobs.py from v67.\n'
        f"Knobs: {json.dumps(asdict(knobs), sort_keys=True)}\n",
        1,
    )
    knob_block = (
        "SCOUT_DELAY_STEP = 24\n"
        f"FINAL_KICK_TURN = {knobs.final_kick_turn}\n"
        f"FINAL_KICK_GAP = {knobs.final_kick_gap}\n"
        f"FINAL_KICK_GATE_MINER = {knobs.gate_miner!r}\n"
        f"FINAL_KICK_GATE_SCOUT = {knobs.gate_scout!r}\n"
    )
    text = _replace_once(text, "SCOUT_DELAY_STEP = 24\n", knob_block)
    text = _replace_once(
        text,
        "    factory_gap = factory_row - south\n\n",
        (
            "    factory_gap = factory_row - south\n"
            "    final_kick = turn >= FINAL_KICK_TURN or factory_gap <= FINAL_KICK_GAP\n\n"
        ),
    )
    text = _replace_once(
        text,
        "        if f_build_cd <= 1 and factory_energy >= 650 and factory_gap > 6 and counts[MINER] < 1:\n",
        (
            "        if (\n"
            "            not (FINAL_KICK_GATE_MINER and final_kick)\n"
            "            and f_build_cd <= 1\n"
            "            and factory_energy >= 650\n"
            "            and factory_gap > 6\n"
            "            and counts[MINER] < 1\n"
            "        ):\n"
        ),
    )
    text = _replace_once(
        text,
        "            turn >= SCOUT_DELAY_STEP\n"
        "            and spawn_ok\n",
        "            turn >= SCOUT_DELAY_STEP\n"
        "            and not (FINAL_KICK_GATE_SCOUT and final_kick)\n"
        "            and spawn_ok\n",
    )
    return text


def micro_space() -> list[Knobs]:
    """Small evidence-first screen around v110 and less aggressive neighbors."""
    raw = [
        (360, 3, True, True),
        (380, 3, True, True),
        (400, 3, True, True),
        (420, 3, True, True),
        (400, 4, True, True),  # v110-equivalent mechanism
        (420, 4, True, True),
        (450, 4, True, True),
        (400, 5, True, False),
        (420, 5, True, False),
        (400, 5, False, True),
        (420, 5, False, True),
        (9999, 4, True, True),  # gap-only gate
    ]
    return [Knobs(*x) for x in raw]


def grid_space() -> list[Knobs]:
    turns = [340, 360, 380, 400, 420, 450, 9999]
    gaps = [2, 3, 4, 5, 6]
    modes = [(True, True), (True, False), (False, True)]
    return [Knobs(t, g, gm, gs) for t in turns for g in gaps for gm, gs in modes]


def random_space(count: int, seed: int) -> list[Knobs]:
    rng = random.Random(seed)
    turns = [320, 340, 360, 380, 400, 420, 450, 480, 9999]
    gaps = [2, 3, 4, 5, 6, 7]
    modes = [(True, True), (True, False), (False, True)]
    seen: set[Knobs] = set()
    while len(seen) < count:
        gm, gs = rng.choice(modes)
        seen.add(Knobs(rng.choice(turns), rng.choice(gaps), gm, gs))
    return sorted(seen, key=lambda k: (k.final_kick_turn, k.final_kick_gap, k.mode))


def build_space(args: argparse.Namespace) -> list[Knobs]:
    if args.preset == "micro":
        knobs = micro_space()
    elif args.preset == "grid":
        knobs = grid_space()
    else:
        knobs = random_space(args.random_count, args.random_seed)
    if args.limit:
        knobs = knobs[: args.limit]
    return knobs


def write_candidate(base_text: str, out_dir: Path, knobs: Knobs) -> Path:
    candidate_dir = out_dir / knobs.name
    candidate_dir.mkdir(parents=True, exist_ok=True)
    agent_path = candidate_dir / "main.py"
    agent_path.write_text(inject_knobs(base_text, knobs), encoding="utf-8")
    (candidate_dir / "knobs.json").write_text(
        json.dumps(asdict(knobs), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return agent_path


def parse_opponents(raw: str | None) -> list[Path]:
    if not raw:
        return DEFAULT_OPPONENTS
    return [Path(p).expanduser().resolve() for p in raw.split(",") if p.strip()]


def run_eval(agent_path: Path, opponent: Path, args: argparse.Namespace) -> dict:
    sys.path.insert(0, str(ROOT / "scripts"))
    from paired_eval_sides import run  # noqa: WPS433

    return run(
        str(agent_path),
        str(opponent),
        seeds=args.seeds,
        start_seed=args.start_seed,
        workers=args.workers,
    )


def decision(row: dict) -> str:
    if row["z"] >= 1.7:
        return "PASS_FAST"
    if row["z"] >= 0.5:
        return "KEEP_FAST"
    if row["z"] >= -0.5:
        return "NEUTRAL"
    return "DROP_FAST"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", type=Path, default=DEFAULT_BASE)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    ap.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    ap.add_argument("--preset", choices=["micro", "grid", "random"], default="micro")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--random-count", type=int, default=24)
    ap.add_argument("--random-seed", type=int, default=0)
    ap.add_argument("--opponents", default=None, help="comma-separated opponent agent paths")
    ap.add_argument("--seeds", type=int, default=12)
    ap.add_argument("--start-seed", type=int, default=0)
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--evaluate", action="store_true")
    ap.add_argument("--clean", action="store_true", help="remove out-dir before generating")
    args = ap.parse_args()

    base = args.base.expanduser().resolve()
    out_dir = args.out_dir.expanduser().resolve()
    results = args.results.expanduser().resolve()
    if not base.is_file():
        raise SystemExit(f"missing base agent: {base}")
    opponents = parse_opponents(args.opponents)
    for opp in opponents:
        if not opp.is_file():
            raise SystemExit(f"missing opponent agent: {opp}")

    if args.clean and out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    results.parent.mkdir(parents=True, exist_ok=True)

    base_text = base.read_text(encoding="utf-8")
    knobs_list = build_space(args)
    rows = []
    manifest = []
    for knobs in knobs_list:
        agent_path = write_candidate(base_text, out_dir, knobs)
        manifest.append({"name": knobs.name, "agent": str(agent_path), **asdict(knobs)})
        print(f"[generate] {knobs.name} -> {agent_path}", flush=True)
        if not args.evaluate:
            continue
        for opponent in opponents:
            print(f"[eval] {knobs.name} vs {opponent.parent.name} ({args.seeds} seeds)", flush=True)
            r = run_eval(agent_path, opponent, args)
            row = {
                **asdict(knobs),
                "candidate": knobs.name,
                "agent": str(agent_path),
                "opponent": str(opponent),
                "opponent_name": opponent.parent.name,
                "seeds": args.seeds,
                "start_seed": args.start_seed,
                **r,
            }
            row["decision"] = decision(row)
            rows.append(row)
            print(
                f"  {row['w']}-{row['l']}-{row['d']} z={row['z']:+.2f} "
                f"reward={row['a_mean']:.0f}/{row['b_mean']:.0f} {row['decision']}",
                flush=True,
            )

    manifest_path = out_dir / "manifest.csv"
    with manifest_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(manifest[0]))
        writer.writeheader()
        writer.writerows(manifest)

    if args.evaluate:
        fieldnames = [
            "candidate",
            "agent",
            "opponent",
            "opponent_name",
            "final_kick_turn",
            "final_kick_gap",
            "gate_miner",
            "gate_scout",
            "seeds",
            "start_seed",
            "games",
            "w",
            "l",
            "d",
            "z",
            "winrate",
            "draw_rate",
            "a_mean",
            "b_mean",
            "p0_wins",
            "p1_wins",
            "side_draws",
            "side_z",
            "decision",
        ]
        with results.open("w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
        print(f"[done] wrote {len(rows)} eval rows to {results}")
    else:
        print(f"[done] generated {len(manifest)} candidates. Use --evaluate to run paired screens.")
    print(f"[done] manifest: {manifest_path}")


if __name__ == "__main__":
    main()
